### ISSUE TITLE
dark mode  input value not visible when focus out.

### ISSUE THREAD

**Issue by rajneshbiz** [akveo/ng2-smart-table#1156]
I'm using nebular ngx-admin and i'm facing some undesired behavior with smart-table cells on dark mode. In fact, after writing on some input, and when focusing out, the input value gets white, so it's invisible. To see the value again I must focus on the input. That's kinda shitty. Notice that I didn't make any change to the original source yet. It seems to be the default behavior (you can see it [here](https://www.akveo.com/ngx-admin/pages/tables/smart-table) )

Is there any way to customize this behavior ? Thanks.

**Comment by Manolomon** [comment]
Hi, you can add the regular input form behavior provided by nebular's theme via scss this way: 

```scss
@import 'themes';

@import '~@nebular/theme/styles/globals';

@include nb-install-component() {
 ::ng-deep {
    ng2-smart-table {
      .form-control {
        background-color: nb-theme(input-basic-background-color);
        border-color: nb-theme(input-basic-border-color);
        border-style: nb-theme(input-border-style);
        border-width: nb-theme(input-border-width);
        color: nb-theme(input-basic-text-color);
        font-family: nb-theme(input-text-font-family);

        &::placeholder {
          color: nb-theme(input-basic-placeholder-text-color);
          font-family: nb-theme(input-placeholder-text-font-family);
          text-overflow: ellipsis;
        }

        &:focus {
          outline: none;
          border-color: nb-theme(input-basic-focus-border-color);
          background-color: nb-theme(input-basic-background-color);
        }

        &:hover {
          border-color: nb-theme(input-basic-hover-border-color);
        }

        &:disabled {
          background-color: nb-theme(input-basic-disabled-background-color);
          border-color: nb-theme(input-basic-disabled-border-color);
          color: nb-theme(input-basic-disabled-text-color);

          &::placeholder {
            color: nb-theme(input-basic-disabled-placeholder-text-color);
          }
        }

        &.input-full-width {
          width: 100%;
        }
      }
    }
  }
}
```

This is the theme-responsive scss used in regular .form-controls featured in [nebular theme](https://github.com/akveo/nebular/blob/884dd668d586d1fc0696a1dce103581e1986f473/src/framework/bootstrap/styles/_forms.scss)
