### ISSUE TITLE
Custom actions with icons overlap

### ISSUE THREAD

**Issue by Dazza666** [akveo/ng2-smart-table#1197]
Hi All, I am having major issues getting custom actions to render, can someone please help?

I have set up my settings like so:

```
  settings = {
    actions:{
      add:false,
      edit:false,
      delete:false,
      custom: [
        {
          name: 'accept',
          title: '<i class="nb-checkmark inline-block width: 50px"></i>',
        },
        {
          name: 'deny',
          title: '<i class="nb-close inline-block width: 50px"></i>',
        },
      ],
    },
    columns: {
      mmsi: {
        title: 'MMSI',
        editable: false,
      },
      state: {
        title: 'State',
        editable: false,
      },
      vendor: {
        title: 'Vendor',
        editable: false,
      },
      userid: {
        title: 'UserId',
        editable: false,
      },
    },
  };
}
```

this produces:

![Screenshot 2020-08-13 at 22 52 00](https://user-images.githubusercontent.com/5719291/90190842-aa0db480-ddb7-11ea-82d7-432bb62c4437.png)

I found on another issue that someone had added the following CSS to override the defaults:

```
:host ::ng-deep tr .ng2-smart-actions{ display: flex; }

:host ::ng-deep nbng2-st-tbody-custom {display: flex;}

:host ::ng-deep ng2-st-tbody-edit-delete a.ng2-smart-action {display: inline-block !important;}
:host ::ng-deep ng2-st-tbody-create-cancel a.ng2-smart-action {display: inline-block !important;}
:host ::ng-deep ng2-st-tbody-custom a.ng2-smart-action.ng2-smart-action-custom-custom {
    display: inline-block;
    width: 80px;
    text-align: center;
}
```

But this produces this output:

![Screenshot 2020-08-13 at 22 59 10](https://user-images.githubusercontent.com/5719291/90191357-a0388100-ddb8-11ea-96dc-44b5225228fe.png)

The buttons are not aligned, the actions border is messed up, and the other columns on the actions look like they are 1 pixel out.

Please, does anyone know how to resolve?

**Comment by Dazza666** [comment]
No one else has had this issue? I can't believe it! Please does anyone have any advice on how to resolve this?

**Comment by michabbb** [comment]
hi,

i had the same problem yesterday and i was able to fix it this way:

```css
.order-table {

  thead th.ng2-smart-actions.ng-star-inserted {
    width: 1em;
  }

  td.ng2-smart-actions {
    float: left !important;

    ng2-st-tbody-custom {
      float: left;
      width: auto;
      display: flex;
      margin-top: 0.5em;

      a.ng2-smart-action.ng2-smart-action-custom-custom {
        margin-left: 0.5em;
      }
    }
  }
}
```

```html
<ng2-smart-table class="order-table"
                                 [settings]="order_settings"
                                 [source]="order_source"
                                 (custom)="onCustomAction($event)">
                </ng2-smart-table>
```
