### ISSUE TITLE
How to change table header Sort Arrow and its color

### ISSUE THREAD

**Issue by nivre** [akveo/ng2-smart-table#722]
Hi!
I was just wondering how to change the Sort Arrow to a different icon and also its color in ng2-smart-table's component.
I tried over-writing the CSS properties but it never worked.
I was able to change the background of the Header Cells and its font-color but the Sort Arrow remains the same color which is dark-gray.

Thank you in advance for your help.

**Comment by nickbyson** [comment]
facing same issue..

**Comment by nickbyson** [comment]
facing same issue..

**Comment by hectoryo** [comment]
I've managed to change the color using css

```css
:host>>>a.ng2-smart-sort-link.sort::after{
  border-bottom: 4px solid white !important;
}
```
