### ISSUE TITLE
Alternating row colors

### ISSUE THREAD

**Issue by darlontrofy** [akveo/ng2-smart-table#840]
Using Angular 4, I tried all the help I found to set alternating row colors but nothing seems to work. Can you please let me know how to set alternating row colors for the ng2 smart table.

**Comment by aefox** [comment]
This component does not support this feature by default. But it is easy to add what you need through css. You can use something like this:

```scss
tbody tr:nth-child(even) {
  background: yellow;
}
tbody tr:nth-child(odd) {
  background: red;
}
```
